
spring:
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  h2:
    console:
      enabled: true
      path: /h2-console
  application:
    name: teste-api
  servlet:
    multipart:
      max-file-size: 50MB
  datasource:
    name: teste_db
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./data/teste
    username: sa
    password: 
  jpa:
    show-sql: true
  sql:
    init:
      platform: org.hibernate.dialect.H2Dialect
      mode: always
server:
  port: 8080

allowedHosts: http://localhost:4200,*